
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'CreateBlockDialog': typeof import("../components/block/CreateBlockDialog.vue")['default']
    'DeleteBlockDialog': typeof import("../components/block/DeleteBlockDialog.vue")['default']
    'EditBlockDialog': typeof import("../components/block/EditBlockDialog.vue")['default']
    'ViewDetailsBlockDialog': typeof import("../components/block/ViewDetailsBlockDialog.vue")['default']
    'AboutCard': typeof import("../components/common/AboutCard.vue")['default']
    'FeatureCard': typeof import("../components/common/FeatureCard.vue")['default']
    'ProjectCard': typeof import("../components/common/ProjectCard.vue")['default']
    'ServiceCard': typeof import("../components/common/ServiceCard.vue")['default']
    'Sidebar': typeof import("../components/common/Sidebar.vue")['default']
    'SidebarItem': typeof import("../components/common/SidebarItem.vue")['default']
    'StatisticCard': typeof import("../components/common/StatisticCard.vue")['default']
    'SubMenuItem': typeof import("../components/common/SubMenuItem.vue")['default']
    'CreateHighContractDialog': typeof import("../components/contract/CreateHighContractDialog.vue")['default']
    'CreateLandContractDialog': typeof import("../components/contract/CreateLandContractDialog.vue")['default']
    'DeleteHighContractDialog': typeof import("../components/contract/DeleteHighContractDialog.vue")['default']
    'DeleteLandContractDialog': typeof import("../components/contract/DeleteLandContractDialog.vue")['default']
    'EditHighContractDialog': typeof import("../components/contract/EditHighContractDialog.vue")['default']
    'EditLandContractDialog': typeof import("../components/contract/EditLandContractDialog.vue")['default']
    'ViewDetailsHighContractDialog': typeof import("../components/contract/ViewDetailsHighContractDialog.vue")['default']
    'ViewDetailsLandContractDialog': typeof import("../components/contract/ViewDetailsLandContractDialog.vue")['default']
    'CreateCustomerDialog': typeof import("../components/customers/CreateCustomerDialog.vue")['default']
    'DeleteCustomerDialog': typeof import("../components/customers/DeleteCustomerDialog.vue")['default']
    'EditCustomerDialog': typeof import("../components/customers/EditCustomerDialog.vue")['default']
    'ViewDetailsCustomerDialog': typeof import("../components/customers/ViewDetailsCustomerDialog.vue")['default']
    'CreateFloorDialog': typeof import("../components/floor/CreateFloorDialog.vue")['default']
    'DeleteFloorDialog': typeof import("../components/floor/DeleteFloorDialog.vue")['default']
    'EditFloorDialog': typeof import("../components/floor/EditFloorDialog.vue")['default']
    'ViewDetailsFloorDialog': typeof import("../components/floor/ViewDetailsFloorDialog.vue")['default']
    'CreateHighAreaDialog': typeof import("../components/high_area/CreateHighAreaDialog.vue")['default']
    'DeleteHighAreaDialog': typeof import("../components/high_area/DeleteHighAreaDialog.vue")['default']
    'EditHighAreaDialog': typeof import("../components/high_area/EditHighAreaDialog.vue")['default']
    'ViewDetailsHighAreaDialog': typeof import("../components/high_area/ViewDetailsHighAreaDialog.vue")['default']
    'CreateHighPaymentProcessDialog': typeof import("../components/high_payment_process/CreateHighPaymentProcessDialog.vue")['default']
    'DeleteHighPaymentProcessDialog': typeof import("../components/high_payment_process/DeleteHighPaymentProcessDialog.vue")['default']
    'EditHighPaymentProcessDialog': typeof import("../components/high_payment_process/EditHighPaymentProcessDialog.vue")['default']
    'CreateLandAreaDialog': typeof import("../components/land_area/CreateLandAreaDialog.vue")['default']
    'DeleteLandAreaDialog': typeof import("../components/land_area/DeleteLandAreaDialog.vue")['default']
    'EditLandAreaDialog': typeof import("../components/land_area/EditLandAreaDialog.vue")['default']
    'ViewDetailsLandAreaDialog': typeof import("../components/land_area/ViewDetailsLandAreaDialog.vue")['default']
    'CreateLandPaymentProcessDialog': typeof import("../components/land_payment_process/CreateLandPaymentProcessDialog.vue")['default']
    'DeleteLandPaymentProcessDialog': typeof import("../components/land_payment_process/DeleteLandPaymentProcessDialog.vue")['default']
    'EditLandPaymentProcessDialog': typeof import("../components/land_payment_process/EditLandPaymentProcessDialog.vue")['default']
    'CreateHighListOwnerDialog': typeof import("../components/list_owner/CreateHighListOwnerDialog.vue")['default']
    'CreateLandListOwnerDialog': typeof import("../components/list_owner/CreateLandListOwnerDialog.vue")['default']
    'DeleteHighListOwnerDialog': typeof import("../components/list_owner/DeleteHighListOwnerDialog.vue")['default']
    'DeleteLandListOwnerDialog': typeof import("../components/list_owner/DeleteLandListOwnerDialog.vue")['default']
    'EditHighListOwnerDialog': typeof import("../components/list_owner/EditHighListOwnerDialog.vue")['default']
    'EditLandListOwnerDialog': typeof import("../components/list_owner/EditLandListOwnerDialog.vue")['default']
    'ViewDetailsHighListOwnerDialog': typeof import("../components/list_owner/ViewDetailsHighListOwnerDialog.vue")['default']
    'ViewDetailsLandListOwnerDialog': typeof import("../components/list_owner/ViewDetailsLandListOwnerDialog.vue")['default']
    'CreateNotificationDialog': typeof import("../components/notifications/CreateNotificationDialog.vue")['default']
    'DeleteNotificationDialog': typeof import("../components/notifications/DeleteNotificationDialog.vue")['default']
    'EditNotificationDialog': typeof import("../components/notifications/EditNotificationDialog.vue")['default']
    'ViewDetailsNotificationDialog': typeof import("../components/notifications/ViewDetailsNotificationDialog.vue")['default']
    'CreatePaymentMethodDialog': typeof import("../components/payment_method/CreatePaymentMethodDialog.vue")['default']
    'DeletePaymentMethodDialog': typeof import("../components/payment_method/DeletePaymentMethodDialog.vue")['default']
    'EditPaymentMethodDialog': typeof import("../components/payment_method/EditPaymentMethodDialog.vue")['default']
    'ViewDetailsPaymentMethodDialog': typeof import("../components/payment_method/ViewDetailsPaymentMethodDialog.vue")['default']
    'CreatePaymentMethodProcessDialog': typeof import("../components/payment_method_process/CreatePaymentMethodProcessDialog.vue")['default']
    'DeletePaymentMethodProcessDialog': typeof import("../components/payment_method_process/DeletePaymentMethodProcessDialog.vue")['default']
    'EditPaymentMethodProcessDialog': typeof import("../components/payment_method_process/EditPaymentMethodProcessDialog.vue")['default']
    'ViewDetailsPaymentMethodProcessDialog': typeof import("../components/payment_method_process/ViewDetailsPaymentMethodProcessDialog.vue")['default']
    'CoordinateProjectSellerDialog': typeof import("../components/project_seller/CoordinateProjectSellerDialog.vue")['default']
    'DeleteProjectSellerDialog': typeof import("../components/project_seller/DeleteProjectSellerDialog.vue")['default']
    'EditProjectSellerDialog': typeof import("../components/project_seller/EditProjectSellerDialog.vue")['default']
    'ViewDetailsProjectSellerDialog': typeof import("../components/project_seller/ViewDetailsProjectSellerDialog.vue")['default']
    'CreateProjectDialog': typeof import("../components/projects/CreateProjectDialog.vue")['default']
    'DeleteProjectDialog': typeof import("../components/projects/DeleteProjectDialog.vue")['default']
    'EditProjectDialog': typeof import("../components/projects/EditProjectDialog.vue")['default']
    'ViewDetailsProjectDialog': typeof import("../components/projects/ViewDetailsProjectDialog.vue")['default']
    'CreateUserDialog': typeof import("../components/users/CreateUserDialog.vue")['default']
    'DeleteUserDialog': typeof import("../components/users/DeleteUserDialog.vue")['default']
    'EditUserDialog': typeof import("../components/users/EditUserDialog.vue")['default']
    'ViewDetailsUserDialog': typeof import("../components/users/ViewDetailsUserDialog.vue")['default']
    'CreateZoneDialog': typeof import("../components/zone/CreateZoneDialog.vue")['default']
    'DeleteZoneDialog': typeof import("../components/zone/DeleteZoneDialog.vue")['default']
    'EditZoneDialog': typeof import("../components/zone/EditZoneDialog.vue")['default']
    'ViewDetailsZoneDialog': typeof import("../components/zone/ViewDetailsZoneDialog.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'AutoComplete': typeof import("primevue/autocomplete")['default']
    'Calendar': typeof import("primevue/calendar")['default']
    'CascadeSelect': typeof import("primevue/cascadeselect")['default']
    'Checkbox': typeof import("primevue/checkbox")['default']
    'Chips': typeof import("primevue/chips")['default']
    'ColorPicker': typeof import("primevue/colorpicker")['default']
    'Dropdown': typeof import("primevue/dropdown")['default']
    'FloatLabel': typeof import("primevue/floatlabel")['default']
    'IconField': typeof import("primevue/iconfield")['default']
    'InputGroup': typeof import("primevue/inputgroup")['default']
    'InputGroupAddon': typeof import("primevue/inputgroupaddon")['default']
    'InputIcon': typeof import("primevue/inputicon")['default']
    'InputMask': typeof import("primevue/inputmask")['default']
    'InputNumber': typeof import("primevue/inputnumber")['default']
    'InputOtp': typeof import("primevue/inputotp")['default']
    'InputSwitch': typeof import("primevue/inputswitch")['default']
    'InputText': typeof import("primevue/inputtext")['default']
    'Knob': typeof import("primevue/knob")['default']
    'Listbox': typeof import("primevue/listbox")['default']
    'MultiSelect': typeof import("primevue/multiselect")['default']
    'Password': typeof import("primevue/password")['default']
    'RadioButton': typeof import("primevue/radiobutton")['default']
    'Rating': typeof import("primevue/rating")['default']
    'SelectButton': typeof import("primevue/selectbutton")['default']
    'Slider': typeof import("primevue/slider")['default']
    'Textarea': typeof import("primevue/textarea")['default']
    'ToggleButton': typeof import("primevue/togglebutton")['default']
    'TreeSelect': typeof import("primevue/treeselect")['default']
    'TriStateCheckbox': typeof import("primevue/tristatecheckbox")['default']
    'Button': typeof import("primevue/button")['default']
    'ButtonGroup': typeof import("primevue/buttongroup")['default']
    'SpeedDial': typeof import("primevue/speeddial")['default']
    'SplitButton': typeof import("primevue/splitbutton")['default']
    'Column': typeof import("primevue/column")['default']
    'Row': typeof import("primevue/row")['default']
    'ColumnGroup': typeof import("primevue/columngroup")['default']
    'DataTable': typeof import("primevue/datatable")['default']
    'DataView': typeof import("primevue/dataview")['default']
    'DataViewLayoutOptions': typeof import("primevue/dataviewlayoutoptions")['default']
    'OrderList': typeof import("primevue/orderlist")['default']
    'OrganizationChart': typeof import("primevue/organizationchart")['default']
    'Paginator': typeof import("primevue/paginator")['default']
    'PickList': typeof import("primevue/picklist")['default']
    'Tree': typeof import("primevue/tree")['default']
    'TreeTable': typeof import("primevue/treetable")['default']
    'Timeline': typeof import("primevue/timeline")['default']
    'VirtualScroller': typeof import("primevue/virtualscroller")['default']
    'Accordion': typeof import("primevue/accordion")['default']
    'AccordionTab': typeof import("primevue/accordiontab")['default']
    'Card': typeof import("primevue/card")['default']
    'DeferredContent': typeof import("primevue/deferredcontent")['default']
    'Divider': typeof import("primevue/divider")['default']
    'Fieldset': typeof import("primevue/fieldset")['default']
    'Panel': typeof import("primevue/panel")['default']
    'ScrollPanel': typeof import("primevue/scrollpanel")['default']
    'Splitter': typeof import("primevue/splitter")['default']
    'SplitterPanel': typeof import("primevue/splitterpanel")['default']
    'Stepper': typeof import("primevue/stepper")['default']
    'StepperPanel': typeof import("primevue/stepperpanel")['default']
    'TabView': typeof import("primevue/tabview")['default']
    'TabPanel': typeof import("primevue/tabpanel")['default']
    'Toolbar': typeof import("primevue/toolbar")['default']
    'ConfirmDialog': typeof import("primevue/confirmdialog")['default']
    'ConfirmPopup': typeof import("primevue/confirmpopup")['default']
    'Dialog': typeof import("primevue/dialog")['default']
    'DynamicDialog': typeof import("primevue/dynamicdialog")['default']
    'OverlayPanel': typeof import("primevue/overlaypanel")['default']
    'FileUpload': typeof import("primevue/fileupload")['default']
    'Breadcrumb': typeof import("primevue/breadcrumb")['default']
    'ContextMenu': typeof import("primevue/contextmenu")['default']
    'Dock': typeof import("primevue/dock")['default']
    'Menu': typeof import("primevue/menu")['default']
    'Menubar': typeof import("primevue/menubar")['default']
    'MegaMenu': typeof import("primevue/megamenu")['default']
    'PanelMenu': typeof import("primevue/panelmenu")['default']
    'Steps': typeof import("primevue/steps")['default']
    'TabMenu': typeof import("primevue/tabmenu")['default']
    'TieredMenu': typeof import("primevue/tieredmenu")['default']
    'Message': typeof import("primevue/message")['default']
    'InlineMessage': typeof import("primevue/inlinemessage")['default']
    'Toast': typeof import("primevue/toast")['default']
    'Carousel': typeof import("primevue/carousel")['default']
    'Galleria': typeof import("primevue/galleria")['default']
    'Image': typeof import("primevue/image")['default']
    'Avatar': typeof import("primevue/avatar")['default']
    'AvatarGroup': typeof import("primevue/avatargroup")['default']
    'Badge': typeof import("primevue/badge")['default']
    'BlockUI': typeof import("primevue/blockui")['default']
    'Chip': typeof import("primevue/chip")['default']
    'Inplace': typeof import("primevue/inplace")['default']
    'MeterGroup': typeof import("primevue/metergroup")['default']
    'ScrollTop': typeof import("primevue/scrolltop")['default']
    'Skeleton': typeof import("primevue/skeleton")['default']
    'ProgressBar': typeof import("primevue/progressbar")['default']
    'ProgressSpinner': typeof import("primevue/progressspinner")['default']
    'Tag': typeof import("primevue/tag")['default']
    'Terminal': typeof import("primevue/terminal")['default']
    'Icon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'IconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'Motion': typeof import("@vueuse/motion")['MotionComponent']
    'MotionGroup': typeof import("@vueuse/motion")['MotionGroupComponent']
    'VitePwaManifest': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
    'NuxtPwaManifest': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
    'NuxtPwaAssets': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
    'PwaAppleImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
    'PwaAppleSplashScreenImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
    'PwaFaviconImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
    'PwaMaskableImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
    'PwaTransparentImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyCreateBlockDialog': typeof import("../components/block/CreateBlockDialog.vue")['default']
    'LazyDeleteBlockDialog': typeof import("../components/block/DeleteBlockDialog.vue")['default']
    'LazyEditBlockDialog': typeof import("../components/block/EditBlockDialog.vue")['default']
    'LazyViewDetailsBlockDialog': typeof import("../components/block/ViewDetailsBlockDialog.vue")['default']
    'LazyAboutCard': typeof import("../components/common/AboutCard.vue")['default']
    'LazyFeatureCard': typeof import("../components/common/FeatureCard.vue")['default']
    'LazyProjectCard': typeof import("../components/common/ProjectCard.vue")['default']
    'LazyServiceCard': typeof import("../components/common/ServiceCard.vue")['default']
    'LazySidebar': typeof import("../components/common/Sidebar.vue")['default']
    'LazySidebarItem': typeof import("../components/common/SidebarItem.vue")['default']
    'LazyStatisticCard': typeof import("../components/common/StatisticCard.vue")['default']
    'LazySubMenuItem': typeof import("../components/common/SubMenuItem.vue")['default']
    'LazyCreateHighContractDialog': typeof import("../components/contract/CreateHighContractDialog.vue")['default']
    'LazyCreateLandContractDialog': typeof import("../components/contract/CreateLandContractDialog.vue")['default']
    'LazyDeleteHighContractDialog': typeof import("../components/contract/DeleteHighContractDialog.vue")['default']
    'LazyDeleteLandContractDialog': typeof import("../components/contract/DeleteLandContractDialog.vue")['default']
    'LazyEditHighContractDialog': typeof import("../components/contract/EditHighContractDialog.vue")['default']
    'LazyEditLandContractDialog': typeof import("../components/contract/EditLandContractDialog.vue")['default']
    'LazyViewDetailsHighContractDialog': typeof import("../components/contract/ViewDetailsHighContractDialog.vue")['default']
    'LazyViewDetailsLandContractDialog': typeof import("../components/contract/ViewDetailsLandContractDialog.vue")['default']
    'LazyCreateCustomerDialog': typeof import("../components/customers/CreateCustomerDialog.vue")['default']
    'LazyDeleteCustomerDialog': typeof import("../components/customers/DeleteCustomerDialog.vue")['default']
    'LazyEditCustomerDialog': typeof import("../components/customers/EditCustomerDialog.vue")['default']
    'LazyViewDetailsCustomerDialog': typeof import("../components/customers/ViewDetailsCustomerDialog.vue")['default']
    'LazyCreateFloorDialog': typeof import("../components/floor/CreateFloorDialog.vue")['default']
    'LazyDeleteFloorDialog': typeof import("../components/floor/DeleteFloorDialog.vue")['default']
    'LazyEditFloorDialog': typeof import("../components/floor/EditFloorDialog.vue")['default']
    'LazyViewDetailsFloorDialog': typeof import("../components/floor/ViewDetailsFloorDialog.vue")['default']
    'LazyCreateHighAreaDialog': typeof import("../components/high_area/CreateHighAreaDialog.vue")['default']
    'LazyDeleteHighAreaDialog': typeof import("../components/high_area/DeleteHighAreaDialog.vue")['default']
    'LazyEditHighAreaDialog': typeof import("../components/high_area/EditHighAreaDialog.vue")['default']
    'LazyViewDetailsHighAreaDialog': typeof import("../components/high_area/ViewDetailsHighAreaDialog.vue")['default']
    'LazyCreateHighPaymentProcessDialog': typeof import("../components/high_payment_process/CreateHighPaymentProcessDialog.vue")['default']
    'LazyDeleteHighPaymentProcessDialog': typeof import("../components/high_payment_process/DeleteHighPaymentProcessDialog.vue")['default']
    'LazyEditHighPaymentProcessDialog': typeof import("../components/high_payment_process/EditHighPaymentProcessDialog.vue")['default']
    'LazyCreateLandAreaDialog': typeof import("../components/land_area/CreateLandAreaDialog.vue")['default']
    'LazyDeleteLandAreaDialog': typeof import("../components/land_area/DeleteLandAreaDialog.vue")['default']
    'LazyEditLandAreaDialog': typeof import("../components/land_area/EditLandAreaDialog.vue")['default']
    'LazyViewDetailsLandAreaDialog': typeof import("../components/land_area/ViewDetailsLandAreaDialog.vue")['default']
    'LazyCreateLandPaymentProcessDialog': typeof import("../components/land_payment_process/CreateLandPaymentProcessDialog.vue")['default']
    'LazyDeleteLandPaymentProcessDialog': typeof import("../components/land_payment_process/DeleteLandPaymentProcessDialog.vue")['default']
    'LazyEditLandPaymentProcessDialog': typeof import("../components/land_payment_process/EditLandPaymentProcessDialog.vue")['default']
    'LazyCreateHighListOwnerDialog': typeof import("../components/list_owner/CreateHighListOwnerDialog.vue")['default']
    'LazyCreateLandListOwnerDialog': typeof import("../components/list_owner/CreateLandListOwnerDialog.vue")['default']
    'LazyDeleteHighListOwnerDialog': typeof import("../components/list_owner/DeleteHighListOwnerDialog.vue")['default']
    'LazyDeleteLandListOwnerDialog': typeof import("../components/list_owner/DeleteLandListOwnerDialog.vue")['default']
    'LazyEditHighListOwnerDialog': typeof import("../components/list_owner/EditHighListOwnerDialog.vue")['default']
    'LazyEditLandListOwnerDialog': typeof import("../components/list_owner/EditLandListOwnerDialog.vue")['default']
    'LazyViewDetailsHighListOwnerDialog': typeof import("../components/list_owner/ViewDetailsHighListOwnerDialog.vue")['default']
    'LazyViewDetailsLandListOwnerDialog': typeof import("../components/list_owner/ViewDetailsLandListOwnerDialog.vue")['default']
    'LazyCreateNotificationDialog': typeof import("../components/notifications/CreateNotificationDialog.vue")['default']
    'LazyDeleteNotificationDialog': typeof import("../components/notifications/DeleteNotificationDialog.vue")['default']
    'LazyEditNotificationDialog': typeof import("../components/notifications/EditNotificationDialog.vue")['default']
    'LazyViewDetailsNotificationDialog': typeof import("../components/notifications/ViewDetailsNotificationDialog.vue")['default']
    'LazyCreatePaymentMethodDialog': typeof import("../components/payment_method/CreatePaymentMethodDialog.vue")['default']
    'LazyDeletePaymentMethodDialog': typeof import("../components/payment_method/DeletePaymentMethodDialog.vue")['default']
    'LazyEditPaymentMethodDialog': typeof import("../components/payment_method/EditPaymentMethodDialog.vue")['default']
    'LazyViewDetailsPaymentMethodDialog': typeof import("../components/payment_method/ViewDetailsPaymentMethodDialog.vue")['default']
    'LazyCreatePaymentMethodProcessDialog': typeof import("../components/payment_method_process/CreatePaymentMethodProcessDialog.vue")['default']
    'LazyDeletePaymentMethodProcessDialog': typeof import("../components/payment_method_process/DeletePaymentMethodProcessDialog.vue")['default']
    'LazyEditPaymentMethodProcessDialog': typeof import("../components/payment_method_process/EditPaymentMethodProcessDialog.vue")['default']
    'LazyViewDetailsPaymentMethodProcessDialog': typeof import("../components/payment_method_process/ViewDetailsPaymentMethodProcessDialog.vue")['default']
    'LazyCoordinateProjectSellerDialog': typeof import("../components/project_seller/CoordinateProjectSellerDialog.vue")['default']
    'LazyDeleteProjectSellerDialog': typeof import("../components/project_seller/DeleteProjectSellerDialog.vue")['default']
    'LazyEditProjectSellerDialog': typeof import("../components/project_seller/EditProjectSellerDialog.vue")['default']
    'LazyViewDetailsProjectSellerDialog': typeof import("../components/project_seller/ViewDetailsProjectSellerDialog.vue")['default']
    'LazyCreateProjectDialog': typeof import("../components/projects/CreateProjectDialog.vue")['default']
    'LazyDeleteProjectDialog': typeof import("../components/projects/DeleteProjectDialog.vue")['default']
    'LazyEditProjectDialog': typeof import("../components/projects/EditProjectDialog.vue")['default']
    'LazyViewDetailsProjectDialog': typeof import("../components/projects/ViewDetailsProjectDialog.vue")['default']
    'LazyCreateUserDialog': typeof import("../components/users/CreateUserDialog.vue")['default']
    'LazyDeleteUserDialog': typeof import("../components/users/DeleteUserDialog.vue")['default']
    'LazyEditUserDialog': typeof import("../components/users/EditUserDialog.vue")['default']
    'LazyViewDetailsUserDialog': typeof import("../components/users/ViewDetailsUserDialog.vue")['default']
    'LazyCreateZoneDialog': typeof import("../components/zone/CreateZoneDialog.vue")['default']
    'LazyDeleteZoneDialog': typeof import("../components/zone/DeleteZoneDialog.vue")['default']
    'LazyEditZoneDialog': typeof import("../components/zone/EditZoneDialog.vue")['default']
    'LazyViewDetailsZoneDialog': typeof import("../components/zone/ViewDetailsZoneDialog.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'LazyAutoComplete': typeof import("primevue/autocomplete")['default']
    'LazyCalendar': typeof import("primevue/calendar")['default']
    'LazyCascadeSelect': typeof import("primevue/cascadeselect")['default']
    'LazyCheckbox': typeof import("primevue/checkbox")['default']
    'LazyChips': typeof import("primevue/chips")['default']
    'LazyColorPicker': typeof import("primevue/colorpicker")['default']
    'LazyDropdown': typeof import("primevue/dropdown")['default']
    'LazyFloatLabel': typeof import("primevue/floatlabel")['default']
    'LazyIconField': typeof import("primevue/iconfield")['default']
    'LazyInputGroup': typeof import("primevue/inputgroup")['default']
    'LazyInputGroupAddon': typeof import("primevue/inputgroupaddon")['default']
    'LazyInputIcon': typeof import("primevue/inputicon")['default']
    'LazyInputMask': typeof import("primevue/inputmask")['default']
    'LazyInputNumber': typeof import("primevue/inputnumber")['default']
    'LazyInputOtp': typeof import("primevue/inputotp")['default']
    'LazyInputSwitch': typeof import("primevue/inputswitch")['default']
    'LazyInputText': typeof import("primevue/inputtext")['default']
    'LazyKnob': typeof import("primevue/knob")['default']
    'LazyListbox': typeof import("primevue/listbox")['default']
    'LazyMultiSelect': typeof import("primevue/multiselect")['default']
    'LazyPassword': typeof import("primevue/password")['default']
    'LazyRadioButton': typeof import("primevue/radiobutton")['default']
    'LazyRating': typeof import("primevue/rating")['default']
    'LazySelectButton': typeof import("primevue/selectbutton")['default']
    'LazySlider': typeof import("primevue/slider")['default']
    'LazyTextarea': typeof import("primevue/textarea")['default']
    'LazyToggleButton': typeof import("primevue/togglebutton")['default']
    'LazyTreeSelect': typeof import("primevue/treeselect")['default']
    'LazyTriStateCheckbox': typeof import("primevue/tristatecheckbox")['default']
    'LazyButton': typeof import("primevue/button")['default']
    'LazyButtonGroup': typeof import("primevue/buttongroup")['default']
    'LazySpeedDial': typeof import("primevue/speeddial")['default']
    'LazySplitButton': typeof import("primevue/splitbutton")['default']
    'LazyColumn': typeof import("primevue/column")['default']
    'LazyRow': typeof import("primevue/row")['default']
    'LazyColumnGroup': typeof import("primevue/columngroup")['default']
    'LazyDataTable': typeof import("primevue/datatable")['default']
    'LazyDataView': typeof import("primevue/dataview")['default']
    'LazyDataViewLayoutOptions': typeof import("primevue/dataviewlayoutoptions")['default']
    'LazyOrderList': typeof import("primevue/orderlist")['default']
    'LazyOrganizationChart': typeof import("primevue/organizationchart")['default']
    'LazyPaginator': typeof import("primevue/paginator")['default']
    'LazyPickList': typeof import("primevue/picklist")['default']
    'LazyTree': typeof import("primevue/tree")['default']
    'LazyTreeTable': typeof import("primevue/treetable")['default']
    'LazyTimeline': typeof import("primevue/timeline")['default']
    'LazyVirtualScroller': typeof import("primevue/virtualscroller")['default']
    'LazyAccordion': typeof import("primevue/accordion")['default']
    'LazyAccordionTab': typeof import("primevue/accordiontab")['default']
    'LazyCard': typeof import("primevue/card")['default']
    'LazyDeferredContent': typeof import("primevue/deferredcontent")['default']
    'LazyDivider': typeof import("primevue/divider")['default']
    'LazyFieldset': typeof import("primevue/fieldset")['default']
    'LazyPanel': typeof import("primevue/panel")['default']
    'LazyScrollPanel': typeof import("primevue/scrollpanel")['default']
    'LazySplitter': typeof import("primevue/splitter")['default']
    'LazySplitterPanel': typeof import("primevue/splitterpanel")['default']
    'LazyStepper': typeof import("primevue/stepper")['default']
    'LazyStepperPanel': typeof import("primevue/stepperpanel")['default']
    'LazyTabView': typeof import("primevue/tabview")['default']
    'LazyTabPanel': typeof import("primevue/tabpanel")['default']
    'LazyToolbar': typeof import("primevue/toolbar")['default']
    'LazyConfirmDialog': typeof import("primevue/confirmdialog")['default']
    'LazyConfirmPopup': typeof import("primevue/confirmpopup")['default']
    'LazyDialog': typeof import("primevue/dialog")['default']
    'LazyDynamicDialog': typeof import("primevue/dynamicdialog")['default']
    'LazyOverlayPanel': typeof import("primevue/overlaypanel")['default']
    'LazyFileUpload': typeof import("primevue/fileupload")['default']
    'LazyBreadcrumb': typeof import("primevue/breadcrumb")['default']
    'LazyContextMenu': typeof import("primevue/contextmenu")['default']
    'LazyDock': typeof import("primevue/dock")['default']
    'LazyMenu': typeof import("primevue/menu")['default']
    'LazyMenubar': typeof import("primevue/menubar")['default']
    'LazyMegaMenu': typeof import("primevue/megamenu")['default']
    'LazyPanelMenu': typeof import("primevue/panelmenu")['default']
    'LazySteps': typeof import("primevue/steps")['default']
    'LazyTabMenu': typeof import("primevue/tabmenu")['default']
    'LazyTieredMenu': typeof import("primevue/tieredmenu")['default']
    'LazyMessage': typeof import("primevue/message")['default']
    'LazyInlineMessage': typeof import("primevue/inlinemessage")['default']
    'LazyToast': typeof import("primevue/toast")['default']
    'LazyCarousel': typeof import("primevue/carousel")['default']
    'LazyGalleria': typeof import("primevue/galleria")['default']
    'LazyImage': typeof import("primevue/image")['default']
    'LazyAvatar': typeof import("primevue/avatar")['default']
    'LazyAvatarGroup': typeof import("primevue/avatargroup")['default']
    'LazyBadge': typeof import("primevue/badge")['default']
    'LazyBlockUI': typeof import("primevue/blockui")['default']
    'LazyChip': typeof import("primevue/chip")['default']
    'LazyInplace': typeof import("primevue/inplace")['default']
    'LazyMeterGroup': typeof import("primevue/metergroup")['default']
    'LazyScrollTop': typeof import("primevue/scrolltop")['default']
    'LazySkeleton': typeof import("primevue/skeleton")['default']
    'LazyProgressBar': typeof import("primevue/progressbar")['default']
    'LazyProgressSpinner': typeof import("primevue/progressspinner")['default']
    'LazyTag': typeof import("primevue/tag")['default']
    'LazyTerminal': typeof import("primevue/terminal")['default']
    'LazyIcon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'LazyIconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'LazyMotion': typeof import("@vueuse/motion")['MotionComponent']
    'LazyMotionGroup': typeof import("@vueuse/motion")['MotionGroupComponent']
    'LazyVitePwaManifest': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
    'LazyNuxtPwaManifest': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
    'LazyNuxtPwaAssets': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
    'LazyPwaAppleImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
    'LazyPwaAppleSplashScreenImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
    'LazyPwaFaviconImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
    'LazyPwaMaskableImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
    'LazyPwaTransparentImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const CreateBlockDialog: typeof import("../components/block/CreateBlockDialog.vue")['default']
export const DeleteBlockDialog: typeof import("../components/block/DeleteBlockDialog.vue")['default']
export const EditBlockDialog: typeof import("../components/block/EditBlockDialog.vue")['default']
export const ViewDetailsBlockDialog: typeof import("../components/block/ViewDetailsBlockDialog.vue")['default']
export const AboutCard: typeof import("../components/common/AboutCard.vue")['default']
export const FeatureCard: typeof import("../components/common/FeatureCard.vue")['default']
export const ProjectCard: typeof import("../components/common/ProjectCard.vue")['default']
export const ServiceCard: typeof import("../components/common/ServiceCard.vue")['default']
export const Sidebar: typeof import("../components/common/Sidebar.vue")['default']
export const SidebarItem: typeof import("../components/common/SidebarItem.vue")['default']
export const StatisticCard: typeof import("../components/common/StatisticCard.vue")['default']
export const SubMenuItem: typeof import("../components/common/SubMenuItem.vue")['default']
export const CreateHighContractDialog: typeof import("../components/contract/CreateHighContractDialog.vue")['default']
export const CreateLandContractDialog: typeof import("../components/contract/CreateLandContractDialog.vue")['default']
export const DeleteHighContractDialog: typeof import("../components/contract/DeleteHighContractDialog.vue")['default']
export const DeleteLandContractDialog: typeof import("../components/contract/DeleteLandContractDialog.vue")['default']
export const EditHighContractDialog: typeof import("../components/contract/EditHighContractDialog.vue")['default']
export const EditLandContractDialog: typeof import("../components/contract/EditLandContractDialog.vue")['default']
export const ViewDetailsHighContractDialog: typeof import("../components/contract/ViewDetailsHighContractDialog.vue")['default']
export const ViewDetailsLandContractDialog: typeof import("../components/contract/ViewDetailsLandContractDialog.vue")['default']
export const CreateCustomerDialog: typeof import("../components/customers/CreateCustomerDialog.vue")['default']
export const DeleteCustomerDialog: typeof import("../components/customers/DeleteCustomerDialog.vue")['default']
export const EditCustomerDialog: typeof import("../components/customers/EditCustomerDialog.vue")['default']
export const ViewDetailsCustomerDialog: typeof import("../components/customers/ViewDetailsCustomerDialog.vue")['default']
export const CreateFloorDialog: typeof import("../components/floor/CreateFloorDialog.vue")['default']
export const DeleteFloorDialog: typeof import("../components/floor/DeleteFloorDialog.vue")['default']
export const EditFloorDialog: typeof import("../components/floor/EditFloorDialog.vue")['default']
export const ViewDetailsFloorDialog: typeof import("../components/floor/ViewDetailsFloorDialog.vue")['default']
export const CreateHighAreaDialog: typeof import("../components/high_area/CreateHighAreaDialog.vue")['default']
export const DeleteHighAreaDialog: typeof import("../components/high_area/DeleteHighAreaDialog.vue")['default']
export const EditHighAreaDialog: typeof import("../components/high_area/EditHighAreaDialog.vue")['default']
export const ViewDetailsHighAreaDialog: typeof import("../components/high_area/ViewDetailsHighAreaDialog.vue")['default']
export const CreateHighPaymentProcessDialog: typeof import("../components/high_payment_process/CreateHighPaymentProcessDialog.vue")['default']
export const DeleteHighPaymentProcessDialog: typeof import("../components/high_payment_process/DeleteHighPaymentProcessDialog.vue")['default']
export const EditHighPaymentProcessDialog: typeof import("../components/high_payment_process/EditHighPaymentProcessDialog.vue")['default']
export const CreateLandAreaDialog: typeof import("../components/land_area/CreateLandAreaDialog.vue")['default']
export const DeleteLandAreaDialog: typeof import("../components/land_area/DeleteLandAreaDialog.vue")['default']
export const EditLandAreaDialog: typeof import("../components/land_area/EditLandAreaDialog.vue")['default']
export const ViewDetailsLandAreaDialog: typeof import("../components/land_area/ViewDetailsLandAreaDialog.vue")['default']
export const CreateLandPaymentProcessDialog: typeof import("../components/land_payment_process/CreateLandPaymentProcessDialog.vue")['default']
export const DeleteLandPaymentProcessDialog: typeof import("../components/land_payment_process/DeleteLandPaymentProcessDialog.vue")['default']
export const EditLandPaymentProcessDialog: typeof import("../components/land_payment_process/EditLandPaymentProcessDialog.vue")['default']
export const CreateHighListOwnerDialog: typeof import("../components/list_owner/CreateHighListOwnerDialog.vue")['default']
export const CreateLandListOwnerDialog: typeof import("../components/list_owner/CreateLandListOwnerDialog.vue")['default']
export const DeleteHighListOwnerDialog: typeof import("../components/list_owner/DeleteHighListOwnerDialog.vue")['default']
export const DeleteLandListOwnerDialog: typeof import("../components/list_owner/DeleteLandListOwnerDialog.vue")['default']
export const EditHighListOwnerDialog: typeof import("../components/list_owner/EditHighListOwnerDialog.vue")['default']
export const EditLandListOwnerDialog: typeof import("../components/list_owner/EditLandListOwnerDialog.vue")['default']
export const ViewDetailsHighListOwnerDialog: typeof import("../components/list_owner/ViewDetailsHighListOwnerDialog.vue")['default']
export const ViewDetailsLandListOwnerDialog: typeof import("../components/list_owner/ViewDetailsLandListOwnerDialog.vue")['default']
export const CreateNotificationDialog: typeof import("../components/notifications/CreateNotificationDialog.vue")['default']
export const DeleteNotificationDialog: typeof import("../components/notifications/DeleteNotificationDialog.vue")['default']
export const EditNotificationDialog: typeof import("../components/notifications/EditNotificationDialog.vue")['default']
export const ViewDetailsNotificationDialog: typeof import("../components/notifications/ViewDetailsNotificationDialog.vue")['default']
export const CreatePaymentMethodDialog: typeof import("../components/payment_method/CreatePaymentMethodDialog.vue")['default']
export const DeletePaymentMethodDialog: typeof import("../components/payment_method/DeletePaymentMethodDialog.vue")['default']
export const EditPaymentMethodDialog: typeof import("../components/payment_method/EditPaymentMethodDialog.vue")['default']
export const ViewDetailsPaymentMethodDialog: typeof import("../components/payment_method/ViewDetailsPaymentMethodDialog.vue")['default']
export const CreatePaymentMethodProcessDialog: typeof import("../components/payment_method_process/CreatePaymentMethodProcessDialog.vue")['default']
export const DeletePaymentMethodProcessDialog: typeof import("../components/payment_method_process/DeletePaymentMethodProcessDialog.vue")['default']
export const EditPaymentMethodProcessDialog: typeof import("../components/payment_method_process/EditPaymentMethodProcessDialog.vue")['default']
export const ViewDetailsPaymentMethodProcessDialog: typeof import("../components/payment_method_process/ViewDetailsPaymentMethodProcessDialog.vue")['default']
export const CoordinateProjectSellerDialog: typeof import("../components/project_seller/CoordinateProjectSellerDialog.vue")['default']
export const DeleteProjectSellerDialog: typeof import("../components/project_seller/DeleteProjectSellerDialog.vue")['default']
export const EditProjectSellerDialog: typeof import("../components/project_seller/EditProjectSellerDialog.vue")['default']
export const ViewDetailsProjectSellerDialog: typeof import("../components/project_seller/ViewDetailsProjectSellerDialog.vue")['default']
export const CreateProjectDialog: typeof import("../components/projects/CreateProjectDialog.vue")['default']
export const DeleteProjectDialog: typeof import("../components/projects/DeleteProjectDialog.vue")['default']
export const EditProjectDialog: typeof import("../components/projects/EditProjectDialog.vue")['default']
export const ViewDetailsProjectDialog: typeof import("../components/projects/ViewDetailsProjectDialog.vue")['default']
export const CreateUserDialog: typeof import("../components/users/CreateUserDialog.vue")['default']
export const DeleteUserDialog: typeof import("../components/users/DeleteUserDialog.vue")['default']
export const EditUserDialog: typeof import("../components/users/EditUserDialog.vue")['default']
export const ViewDetailsUserDialog: typeof import("../components/users/ViewDetailsUserDialog.vue")['default']
export const CreateZoneDialog: typeof import("../components/zone/CreateZoneDialog.vue")['default']
export const DeleteZoneDialog: typeof import("../components/zone/DeleteZoneDialog.vue")['default']
export const EditZoneDialog: typeof import("../components/zone/EditZoneDialog.vue")['default']
export const ViewDetailsZoneDialog: typeof import("../components/zone/ViewDetailsZoneDialog.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const AutoComplete: typeof import("primevue/autocomplete")['default']
export const Calendar: typeof import("primevue/calendar")['default']
export const CascadeSelect: typeof import("primevue/cascadeselect")['default']
export const Checkbox: typeof import("primevue/checkbox")['default']
export const Chips: typeof import("primevue/chips")['default']
export const ColorPicker: typeof import("primevue/colorpicker")['default']
export const Dropdown: typeof import("primevue/dropdown")['default']
export const FloatLabel: typeof import("primevue/floatlabel")['default']
export const IconField: typeof import("primevue/iconfield")['default']
export const InputGroup: typeof import("primevue/inputgroup")['default']
export const InputGroupAddon: typeof import("primevue/inputgroupaddon")['default']
export const InputIcon: typeof import("primevue/inputicon")['default']
export const InputMask: typeof import("primevue/inputmask")['default']
export const InputNumber: typeof import("primevue/inputnumber")['default']
export const InputOtp: typeof import("primevue/inputotp")['default']
export const InputSwitch: typeof import("primevue/inputswitch")['default']
export const InputText: typeof import("primevue/inputtext")['default']
export const Knob: typeof import("primevue/knob")['default']
export const Listbox: typeof import("primevue/listbox")['default']
export const MultiSelect: typeof import("primevue/multiselect")['default']
export const Password: typeof import("primevue/password")['default']
export const RadioButton: typeof import("primevue/radiobutton")['default']
export const Rating: typeof import("primevue/rating")['default']
export const SelectButton: typeof import("primevue/selectbutton")['default']
export const Slider: typeof import("primevue/slider")['default']
export const Textarea: typeof import("primevue/textarea")['default']
export const ToggleButton: typeof import("primevue/togglebutton")['default']
export const TreeSelect: typeof import("primevue/treeselect")['default']
export const TriStateCheckbox: typeof import("primevue/tristatecheckbox")['default']
export const Button: typeof import("primevue/button")['default']
export const ButtonGroup: typeof import("primevue/buttongroup")['default']
export const SpeedDial: typeof import("primevue/speeddial")['default']
export const SplitButton: typeof import("primevue/splitbutton")['default']
export const Column: typeof import("primevue/column")['default']
export const Row: typeof import("primevue/row")['default']
export const ColumnGroup: typeof import("primevue/columngroup")['default']
export const DataTable: typeof import("primevue/datatable")['default']
export const DataView: typeof import("primevue/dataview")['default']
export const DataViewLayoutOptions: typeof import("primevue/dataviewlayoutoptions")['default']
export const OrderList: typeof import("primevue/orderlist")['default']
export const OrganizationChart: typeof import("primevue/organizationchart")['default']
export const Paginator: typeof import("primevue/paginator")['default']
export const PickList: typeof import("primevue/picklist")['default']
export const Tree: typeof import("primevue/tree")['default']
export const TreeTable: typeof import("primevue/treetable")['default']
export const Timeline: typeof import("primevue/timeline")['default']
export const VirtualScroller: typeof import("primevue/virtualscroller")['default']
export const Accordion: typeof import("primevue/accordion")['default']
export const AccordionTab: typeof import("primevue/accordiontab")['default']
export const Card: typeof import("primevue/card")['default']
export const DeferredContent: typeof import("primevue/deferredcontent")['default']
export const Divider: typeof import("primevue/divider")['default']
export const Fieldset: typeof import("primevue/fieldset")['default']
export const Panel: typeof import("primevue/panel")['default']
export const ScrollPanel: typeof import("primevue/scrollpanel")['default']
export const Splitter: typeof import("primevue/splitter")['default']
export const SplitterPanel: typeof import("primevue/splitterpanel")['default']
export const Stepper: typeof import("primevue/stepper")['default']
export const StepperPanel: typeof import("primevue/stepperpanel")['default']
export const TabView: typeof import("primevue/tabview")['default']
export const TabPanel: typeof import("primevue/tabpanel")['default']
export const Toolbar: typeof import("primevue/toolbar")['default']
export const ConfirmDialog: typeof import("primevue/confirmdialog")['default']
export const ConfirmPopup: typeof import("primevue/confirmpopup")['default']
export const Dialog: typeof import("primevue/dialog")['default']
export const DynamicDialog: typeof import("primevue/dynamicdialog")['default']
export const OverlayPanel: typeof import("primevue/overlaypanel")['default']
export const FileUpload: typeof import("primevue/fileupload")['default']
export const Breadcrumb: typeof import("primevue/breadcrumb")['default']
export const ContextMenu: typeof import("primevue/contextmenu")['default']
export const Dock: typeof import("primevue/dock")['default']
export const Menu: typeof import("primevue/menu")['default']
export const Menubar: typeof import("primevue/menubar")['default']
export const MegaMenu: typeof import("primevue/megamenu")['default']
export const PanelMenu: typeof import("primevue/panelmenu")['default']
export const Steps: typeof import("primevue/steps")['default']
export const TabMenu: typeof import("primevue/tabmenu")['default']
export const TieredMenu: typeof import("primevue/tieredmenu")['default']
export const Message: typeof import("primevue/message")['default']
export const InlineMessage: typeof import("primevue/inlinemessage")['default']
export const Toast: typeof import("primevue/toast")['default']
export const Carousel: typeof import("primevue/carousel")['default']
export const Galleria: typeof import("primevue/galleria")['default']
export const Image: typeof import("primevue/image")['default']
export const Avatar: typeof import("primevue/avatar")['default']
export const AvatarGroup: typeof import("primevue/avatargroup")['default']
export const Badge: typeof import("primevue/badge")['default']
export const BlockUI: typeof import("primevue/blockui")['default']
export const Chip: typeof import("primevue/chip")['default']
export const Inplace: typeof import("primevue/inplace")['default']
export const MeterGroup: typeof import("primevue/metergroup")['default']
export const ScrollTop: typeof import("primevue/scrolltop")['default']
export const Skeleton: typeof import("primevue/skeleton")['default']
export const ProgressBar: typeof import("primevue/progressbar")['default']
export const ProgressSpinner: typeof import("primevue/progressspinner")['default']
export const Tag: typeof import("primevue/tag")['default']
export const Terminal: typeof import("primevue/terminal")['default']
export const Icon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const IconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const Motion: typeof import("@vueuse/motion")['MotionComponent']
export const MotionGroup: typeof import("@vueuse/motion")['MotionGroupComponent']
export const VitePwaManifest: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const NuxtPwaManifest: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const NuxtPwaAssets: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
export const PwaAppleImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
export const PwaAppleSplashScreenImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
export const PwaFaviconImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
export const PwaMaskableImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
export const PwaTransparentImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyCreateBlockDialog: typeof import("../components/block/CreateBlockDialog.vue")['default']
export const LazyDeleteBlockDialog: typeof import("../components/block/DeleteBlockDialog.vue")['default']
export const LazyEditBlockDialog: typeof import("../components/block/EditBlockDialog.vue")['default']
export const LazyViewDetailsBlockDialog: typeof import("../components/block/ViewDetailsBlockDialog.vue")['default']
export const LazyAboutCard: typeof import("../components/common/AboutCard.vue")['default']
export const LazyFeatureCard: typeof import("../components/common/FeatureCard.vue")['default']
export const LazyProjectCard: typeof import("../components/common/ProjectCard.vue")['default']
export const LazyServiceCard: typeof import("../components/common/ServiceCard.vue")['default']
export const LazySidebar: typeof import("../components/common/Sidebar.vue")['default']
export const LazySidebarItem: typeof import("../components/common/SidebarItem.vue")['default']
export const LazyStatisticCard: typeof import("../components/common/StatisticCard.vue")['default']
export const LazySubMenuItem: typeof import("../components/common/SubMenuItem.vue")['default']
export const LazyCreateHighContractDialog: typeof import("../components/contract/CreateHighContractDialog.vue")['default']
export const LazyCreateLandContractDialog: typeof import("../components/contract/CreateLandContractDialog.vue")['default']
export const LazyDeleteHighContractDialog: typeof import("../components/contract/DeleteHighContractDialog.vue")['default']
export const LazyDeleteLandContractDialog: typeof import("../components/contract/DeleteLandContractDialog.vue")['default']
export const LazyEditHighContractDialog: typeof import("../components/contract/EditHighContractDialog.vue")['default']
export const LazyEditLandContractDialog: typeof import("../components/contract/EditLandContractDialog.vue")['default']
export const LazyViewDetailsHighContractDialog: typeof import("../components/contract/ViewDetailsHighContractDialog.vue")['default']
export const LazyViewDetailsLandContractDialog: typeof import("../components/contract/ViewDetailsLandContractDialog.vue")['default']
export const LazyCreateCustomerDialog: typeof import("../components/customers/CreateCustomerDialog.vue")['default']
export const LazyDeleteCustomerDialog: typeof import("../components/customers/DeleteCustomerDialog.vue")['default']
export const LazyEditCustomerDialog: typeof import("../components/customers/EditCustomerDialog.vue")['default']
export const LazyViewDetailsCustomerDialog: typeof import("../components/customers/ViewDetailsCustomerDialog.vue")['default']
export const LazyCreateFloorDialog: typeof import("../components/floor/CreateFloorDialog.vue")['default']
export const LazyDeleteFloorDialog: typeof import("../components/floor/DeleteFloorDialog.vue")['default']
export const LazyEditFloorDialog: typeof import("../components/floor/EditFloorDialog.vue")['default']
export const LazyViewDetailsFloorDialog: typeof import("../components/floor/ViewDetailsFloorDialog.vue")['default']
export const LazyCreateHighAreaDialog: typeof import("../components/high_area/CreateHighAreaDialog.vue")['default']
export const LazyDeleteHighAreaDialog: typeof import("../components/high_area/DeleteHighAreaDialog.vue")['default']
export const LazyEditHighAreaDialog: typeof import("../components/high_area/EditHighAreaDialog.vue")['default']
export const LazyViewDetailsHighAreaDialog: typeof import("../components/high_area/ViewDetailsHighAreaDialog.vue")['default']
export const LazyCreateHighPaymentProcessDialog: typeof import("../components/high_payment_process/CreateHighPaymentProcessDialog.vue")['default']
export const LazyDeleteHighPaymentProcessDialog: typeof import("../components/high_payment_process/DeleteHighPaymentProcessDialog.vue")['default']
export const LazyEditHighPaymentProcessDialog: typeof import("../components/high_payment_process/EditHighPaymentProcessDialog.vue")['default']
export const LazyCreateLandAreaDialog: typeof import("../components/land_area/CreateLandAreaDialog.vue")['default']
export const LazyDeleteLandAreaDialog: typeof import("../components/land_area/DeleteLandAreaDialog.vue")['default']
export const LazyEditLandAreaDialog: typeof import("../components/land_area/EditLandAreaDialog.vue")['default']
export const LazyViewDetailsLandAreaDialog: typeof import("../components/land_area/ViewDetailsLandAreaDialog.vue")['default']
export const LazyCreateLandPaymentProcessDialog: typeof import("../components/land_payment_process/CreateLandPaymentProcessDialog.vue")['default']
export const LazyDeleteLandPaymentProcessDialog: typeof import("../components/land_payment_process/DeleteLandPaymentProcessDialog.vue")['default']
export const LazyEditLandPaymentProcessDialog: typeof import("../components/land_payment_process/EditLandPaymentProcessDialog.vue")['default']
export const LazyCreateHighListOwnerDialog: typeof import("../components/list_owner/CreateHighListOwnerDialog.vue")['default']
export const LazyCreateLandListOwnerDialog: typeof import("../components/list_owner/CreateLandListOwnerDialog.vue")['default']
export const LazyDeleteHighListOwnerDialog: typeof import("../components/list_owner/DeleteHighListOwnerDialog.vue")['default']
export const LazyDeleteLandListOwnerDialog: typeof import("../components/list_owner/DeleteLandListOwnerDialog.vue")['default']
export const LazyEditHighListOwnerDialog: typeof import("../components/list_owner/EditHighListOwnerDialog.vue")['default']
export const LazyEditLandListOwnerDialog: typeof import("../components/list_owner/EditLandListOwnerDialog.vue")['default']
export const LazyViewDetailsHighListOwnerDialog: typeof import("../components/list_owner/ViewDetailsHighListOwnerDialog.vue")['default']
export const LazyViewDetailsLandListOwnerDialog: typeof import("../components/list_owner/ViewDetailsLandListOwnerDialog.vue")['default']
export const LazyCreateNotificationDialog: typeof import("../components/notifications/CreateNotificationDialog.vue")['default']
export const LazyDeleteNotificationDialog: typeof import("../components/notifications/DeleteNotificationDialog.vue")['default']
export const LazyEditNotificationDialog: typeof import("../components/notifications/EditNotificationDialog.vue")['default']
export const LazyViewDetailsNotificationDialog: typeof import("../components/notifications/ViewDetailsNotificationDialog.vue")['default']
export const LazyCreatePaymentMethodDialog: typeof import("../components/payment_method/CreatePaymentMethodDialog.vue")['default']
export const LazyDeletePaymentMethodDialog: typeof import("../components/payment_method/DeletePaymentMethodDialog.vue")['default']
export const LazyEditPaymentMethodDialog: typeof import("../components/payment_method/EditPaymentMethodDialog.vue")['default']
export const LazyViewDetailsPaymentMethodDialog: typeof import("../components/payment_method/ViewDetailsPaymentMethodDialog.vue")['default']
export const LazyCreatePaymentMethodProcessDialog: typeof import("../components/payment_method_process/CreatePaymentMethodProcessDialog.vue")['default']
export const LazyDeletePaymentMethodProcessDialog: typeof import("../components/payment_method_process/DeletePaymentMethodProcessDialog.vue")['default']
export const LazyEditPaymentMethodProcessDialog: typeof import("../components/payment_method_process/EditPaymentMethodProcessDialog.vue")['default']
export const LazyViewDetailsPaymentMethodProcessDialog: typeof import("../components/payment_method_process/ViewDetailsPaymentMethodProcessDialog.vue")['default']
export const LazyCoordinateProjectSellerDialog: typeof import("../components/project_seller/CoordinateProjectSellerDialog.vue")['default']
export const LazyDeleteProjectSellerDialog: typeof import("../components/project_seller/DeleteProjectSellerDialog.vue")['default']
export const LazyEditProjectSellerDialog: typeof import("../components/project_seller/EditProjectSellerDialog.vue")['default']
export const LazyViewDetailsProjectSellerDialog: typeof import("../components/project_seller/ViewDetailsProjectSellerDialog.vue")['default']
export const LazyCreateProjectDialog: typeof import("../components/projects/CreateProjectDialog.vue")['default']
export const LazyDeleteProjectDialog: typeof import("../components/projects/DeleteProjectDialog.vue")['default']
export const LazyEditProjectDialog: typeof import("../components/projects/EditProjectDialog.vue")['default']
export const LazyViewDetailsProjectDialog: typeof import("../components/projects/ViewDetailsProjectDialog.vue")['default']
export const LazyCreateUserDialog: typeof import("../components/users/CreateUserDialog.vue")['default']
export const LazyDeleteUserDialog: typeof import("../components/users/DeleteUserDialog.vue")['default']
export const LazyEditUserDialog: typeof import("../components/users/EditUserDialog.vue")['default']
export const LazyViewDetailsUserDialog: typeof import("../components/users/ViewDetailsUserDialog.vue")['default']
export const LazyCreateZoneDialog: typeof import("../components/zone/CreateZoneDialog.vue")['default']
export const LazyDeleteZoneDialog: typeof import("../components/zone/DeleteZoneDialog.vue")['default']
export const LazyEditZoneDialog: typeof import("../components/zone/EditZoneDialog.vue")['default']
export const LazyViewDetailsZoneDialog: typeof import("../components/zone/ViewDetailsZoneDialog.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const LazyAutoComplete: typeof import("primevue/autocomplete")['default']
export const LazyCalendar: typeof import("primevue/calendar")['default']
export const LazyCascadeSelect: typeof import("primevue/cascadeselect")['default']
export const LazyCheckbox: typeof import("primevue/checkbox")['default']
export const LazyChips: typeof import("primevue/chips")['default']
export const LazyColorPicker: typeof import("primevue/colorpicker")['default']
export const LazyDropdown: typeof import("primevue/dropdown")['default']
export const LazyFloatLabel: typeof import("primevue/floatlabel")['default']
export const LazyIconField: typeof import("primevue/iconfield")['default']
export const LazyInputGroup: typeof import("primevue/inputgroup")['default']
export const LazyInputGroupAddon: typeof import("primevue/inputgroupaddon")['default']
export const LazyInputIcon: typeof import("primevue/inputicon")['default']
export const LazyInputMask: typeof import("primevue/inputmask")['default']
export const LazyInputNumber: typeof import("primevue/inputnumber")['default']
export const LazyInputOtp: typeof import("primevue/inputotp")['default']
export const LazyInputSwitch: typeof import("primevue/inputswitch")['default']
export const LazyInputText: typeof import("primevue/inputtext")['default']
export const LazyKnob: typeof import("primevue/knob")['default']
export const LazyListbox: typeof import("primevue/listbox")['default']
export const LazyMultiSelect: typeof import("primevue/multiselect")['default']
export const LazyPassword: typeof import("primevue/password")['default']
export const LazyRadioButton: typeof import("primevue/radiobutton")['default']
export const LazyRating: typeof import("primevue/rating")['default']
export const LazySelectButton: typeof import("primevue/selectbutton")['default']
export const LazySlider: typeof import("primevue/slider")['default']
export const LazyTextarea: typeof import("primevue/textarea")['default']
export const LazyToggleButton: typeof import("primevue/togglebutton")['default']
export const LazyTreeSelect: typeof import("primevue/treeselect")['default']
export const LazyTriStateCheckbox: typeof import("primevue/tristatecheckbox")['default']
export const LazyButton: typeof import("primevue/button")['default']
export const LazyButtonGroup: typeof import("primevue/buttongroup")['default']
export const LazySpeedDial: typeof import("primevue/speeddial")['default']
export const LazySplitButton: typeof import("primevue/splitbutton")['default']
export const LazyColumn: typeof import("primevue/column")['default']
export const LazyRow: typeof import("primevue/row")['default']
export const LazyColumnGroup: typeof import("primevue/columngroup")['default']
export const LazyDataTable: typeof import("primevue/datatable")['default']
export const LazyDataView: typeof import("primevue/dataview")['default']
export const LazyDataViewLayoutOptions: typeof import("primevue/dataviewlayoutoptions")['default']
export const LazyOrderList: typeof import("primevue/orderlist")['default']
export const LazyOrganizationChart: typeof import("primevue/organizationchart")['default']
export const LazyPaginator: typeof import("primevue/paginator")['default']
export const LazyPickList: typeof import("primevue/picklist")['default']
export const LazyTree: typeof import("primevue/tree")['default']
export const LazyTreeTable: typeof import("primevue/treetable")['default']
export const LazyTimeline: typeof import("primevue/timeline")['default']
export const LazyVirtualScroller: typeof import("primevue/virtualscroller")['default']
export const LazyAccordion: typeof import("primevue/accordion")['default']
export const LazyAccordionTab: typeof import("primevue/accordiontab")['default']
export const LazyCard: typeof import("primevue/card")['default']
export const LazyDeferredContent: typeof import("primevue/deferredcontent")['default']
export const LazyDivider: typeof import("primevue/divider")['default']
export const LazyFieldset: typeof import("primevue/fieldset")['default']
export const LazyPanel: typeof import("primevue/panel")['default']
export const LazyScrollPanel: typeof import("primevue/scrollpanel")['default']
export const LazySplitter: typeof import("primevue/splitter")['default']
export const LazySplitterPanel: typeof import("primevue/splitterpanel")['default']
export const LazyStepper: typeof import("primevue/stepper")['default']
export const LazyStepperPanel: typeof import("primevue/stepperpanel")['default']
export const LazyTabView: typeof import("primevue/tabview")['default']
export const LazyTabPanel: typeof import("primevue/tabpanel")['default']
export const LazyToolbar: typeof import("primevue/toolbar")['default']
export const LazyConfirmDialog: typeof import("primevue/confirmdialog")['default']
export const LazyConfirmPopup: typeof import("primevue/confirmpopup")['default']
export const LazyDialog: typeof import("primevue/dialog")['default']
export const LazyDynamicDialog: typeof import("primevue/dynamicdialog")['default']
export const LazyOverlayPanel: typeof import("primevue/overlaypanel")['default']
export const LazyFileUpload: typeof import("primevue/fileupload")['default']
export const LazyBreadcrumb: typeof import("primevue/breadcrumb")['default']
export const LazyContextMenu: typeof import("primevue/contextmenu")['default']
export const LazyDock: typeof import("primevue/dock")['default']
export const LazyMenu: typeof import("primevue/menu")['default']
export const LazyMenubar: typeof import("primevue/menubar")['default']
export const LazyMegaMenu: typeof import("primevue/megamenu")['default']
export const LazyPanelMenu: typeof import("primevue/panelmenu")['default']
export const LazySteps: typeof import("primevue/steps")['default']
export const LazyTabMenu: typeof import("primevue/tabmenu")['default']
export const LazyTieredMenu: typeof import("primevue/tieredmenu")['default']
export const LazyMessage: typeof import("primevue/message")['default']
export const LazyInlineMessage: typeof import("primevue/inlinemessage")['default']
export const LazyToast: typeof import("primevue/toast")['default']
export const LazyCarousel: typeof import("primevue/carousel")['default']
export const LazyGalleria: typeof import("primevue/galleria")['default']
export const LazyImage: typeof import("primevue/image")['default']
export const LazyAvatar: typeof import("primevue/avatar")['default']
export const LazyAvatarGroup: typeof import("primevue/avatargroup")['default']
export const LazyBadge: typeof import("primevue/badge")['default']
export const LazyBlockUI: typeof import("primevue/blockui")['default']
export const LazyChip: typeof import("primevue/chip")['default']
export const LazyInplace: typeof import("primevue/inplace")['default']
export const LazyMeterGroup: typeof import("primevue/metergroup")['default']
export const LazyScrollTop: typeof import("primevue/scrolltop")['default']
export const LazySkeleton: typeof import("primevue/skeleton")['default']
export const LazyProgressBar: typeof import("primevue/progressbar")['default']
export const LazyProgressSpinner: typeof import("primevue/progressspinner")['default']
export const LazyTag: typeof import("primevue/tag")['default']
export const LazyTerminal: typeof import("primevue/terminal")['default']
export const LazyIcon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const LazyIconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const LazyMotion: typeof import("@vueuse/motion")['MotionComponent']
export const LazyMotionGroup: typeof import("@vueuse/motion")['MotionGroupComponent']
export const LazyVitePwaManifest: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const LazyNuxtPwaManifest: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const LazyNuxtPwaAssets: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
export const LazyPwaAppleImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
export const LazyPwaAppleSplashScreenImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
export const LazyPwaFaviconImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
export const LazyPwaMaskableImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
export const LazyPwaTransparentImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
